### ISSUE TITLE
Add installer for Windows

### ISSUE THREAD

**Issue by totkeks** [NeverSinkDev/NeverSink-Filter-for-PoE2#12]
Hey Neversink,

how do you feel about a little PowerShell script to copy the file to the correct directory automatically?

For people that clone the repo, like me, this would help.

For people that don't use git, they could potentially run `Invoke-WebRequest`, though that means they have to trust you. :-D

**Comment by andrewrkerr** [comment]
The Windows powershell script is really just a one liner to download the filter:

curl https://raw.githubusercontent.com/NeverSinkDev/NeverSink-PoE2litefilter/refs/heads/main/NeverSinks%20Litefilter.filter -o "$($ENV:userprofile)\Documents\My Games\Path of Exile 2\NeverSinks-Litefilter.filter"

**Comment by abevol** [comment]
The version with http-proxy:
`Invoke-WebRequest https://raw.githubusercontent.com/NeverSinkDev/NeverSink-PoE2litefilter/refs/heads/main/NeverSinks%20Litefilter.filter -OutFile "$($ENV:userprofile)\Documents\My Games\Path of Exile 2\NeverSinks-Litefilter.filter" -Proxy "http://127.0.0.1:7777"`

**Comment by NeverSinkDev** [comment]
I think I'll pass on this one. 

It's true that this is more comfortable and intuitive, but I see some dangers here, that users might start thinking filters require an installer and that trust can be abused by others.

This filter is at most temporary and I hope we'll be back to subscription/filterblade-export style filters soon.
