### ISSUE TITLE
Filed to load item filter

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [NeverSinkDev/NeverSink-Filter-for-PoE2#16]
Filed to load item filter. Reason: Line 7: Unknown rule type <!DOCTYPE

![image](https://github.com/user-attachments/assets/ff2072ac-d1ee-4c50-9470-1d03f707299a)

**Comment by Gbury** [comment]
I may be wrong, but from the error it looks like you copy-pasted/downloaded a webpage rather than the filter file itself ?

**Comment by bratzie** [comment]
Yep, you most likely right clicked here in GitHub and sepected "Save as..." which saves the webpage, not the filter. Download the zip here: https://github.com/NeverSinkDev/NeverSink-PoE2litefilter/releases/tag/0.1.2 and extract the `.filter` file and copy that to the correct folder.

**Comment by abevol** [comment]
Try this #12

**Comment by IlyaKarpelyuk** [comment]
> I may be wrong, but from the error it looks like you copy-pasted/downloaded a webpage rather than the filter file itself ?

You are right. I downloaded the correct file and the filter works.
