### ISSUE TITLE
Superior Items Suggestion

### ISSUE THREAD

**Issue by bakerj417** [NeverSinkDev/NeverSink-Filter-for-PoE2#18]
Seems like any superior gear/weapons should have diff color and  sound since you can workbench them for the resources. Thanks for the filter!!!

**Comment by bakerj417** [comment]
NVM, saw in the filter that those setting aren't working. closing...

**Comment by NoteThatHard** [comment]
They are working, just for quality above 10%, you can change that value. Refer to #11 for more details.
