### ISSUE TITLE
Now hides every item

### ISSUE THREAD

**Issue by zhongjiedong** [NeverSinkDev/NeverSink-Filter-for-PoE2#21]
Every piece of loot is now hidden including valuable currency drops

**Comment by TheSakkeus** [comment]
Theres a new patch, this was to be expected.
Can only wait for him to update his work.

Thanks for work in advance.

edit: 

Im using filter 0.1.2
![state](https://github.com/user-attachments/assets/2786044f-1e1c-4635-bec6-9676b253dcfe)

**Comment by Tadiian** [comment]
Don't have this Issue.

**Comment by egeturker** [comment]
@zhongjiedong Check out if you pressed 'Z' key that hides all loot.

**Comment by zhongjiedong** [comment]
> @zhongjiedong Check out if you pressed 'Z' key that hides all loot.

thanks, this was it
