### ISSUE TITLE
Excavated Chests highlight

### ISSUE THREAD

**Issue by dchrzanowski** [NeverSinkDev/NeverSink-Filter-for-PoE2#22]
Hi, thank you for your great work NeverSink. Excavated Chests blend with the rest of the white items a bit much, some highlight to them would be nice. No rush on this of course. Thank you!

**Comment by NeverSinkDev** [comment]
Nothing can be done about this, item filters can't affect chests.
I recommend contacting GGG about it or making a forum thread.
