### ISSUE TITLE
Not displaying superior objects differently

### ISSUE THREAD

**Issue by javicavi** [NeverSinkDev/NeverSink-Filter-for-PoE2#23]
Hi NeverSink, first of all, thanks a lot for your work. I’ve noticed that superior items are not displayed differently from the regular ones, and I belive it would be appropriate to add some distinction to them, as they are quite useful when it comes to obtaining parts at the salvage bench.

![imagen](https://github.com/user-attachments/assets/c7adb7bf-6efa-4542-94be-1006214e2903)

**Comment by NoteThatHard** [comment]
This was addressed in #11 and #18 .

**Comment by NeverSinkDev** [comment]
Was addressed, will receive further improvements soon

**Comment by javicavi** [comment]
I didn't realize it had already been addressed, my bad.
