### ISSUE TITLE
Filter Won’t Install on Steam Deck

### ISSUE THREAD

**Issue by willshattuck** [NeverSinkDev/NeverSink-Filter-for-PoE2#24]
Hi. Thanks for all your work. I know this may be an esoteric request. I’m having problems getting the filter to work on my steam deck. I admit I don’t know if it’s possible due to how the steam deck implements games which I don’t know how it does at this time. 

On my Windows computer I have successfully added the Neversink filter.  I have found the folder in Steam Deck Desktop mode.  I downloaded the zip, extracted, used the file manager to navigate to (.local/.../steamapps/compatdata/2694490/pfx/drive\_c/users/steamuser/My Documents/My Games/Path of Exile 2) and copied the filter do this location.  

However, when I go into POE2, Options, Game then try to select the filter it doesn't exist.  When I click the Folder icon it brings up a file manager that feels like WINE or an older version of a Linux desktop environment.  And the file I copied above in desktop mode does not show up here.  I assume it's because it's an emulated environment.  

How would I copy the Neversink Item filter to appear in the POE2 options?

Thanks for any suggestions.

**Comment by NeverSinkDev** [comment]
This is not an issue of the filter, I'm trying to keep the repo clean. Please ask in the discord, you'll have more chances of getting answers there anyway.
