### ISSUE TITLE
Quality highlight is > 10

### ISSUE THREAD

**Issue by phadej** [NeverSinkDev/NeverSink-Filter-for-PoE2#28]
Is this intentional?

Many superior items (which can be salvaged for 1 scrap) are not highlighted

**Comment by Ezahiel** [comment]
> Is this intentional?
> 
> Many superior items (which can be salvaged for 1 scrap) are not highlighted

you can check [here](https://github.com/NeverSinkDev/NeverSink-PoE2litefilter/pull/3#issuecomment-2539759587)
Since its working fine for me and lowered initial value from 10 to 5+, but if you wanna lower it even more it should work too(didn't tested )

**Comment by NickGrease** [comment]
> Is this intentional?
> Many superior items (which can be salvaged for 1 scrap) are not highlighted

Early/New game you definitely want all Superior items highlighted, late/end game you don't want to waste inventory space on less the 2 scraps/or you're looking for bases that are already mostly qualitied up. Not really possible (I don't think) to solve both with one filter, so I guess late game took precedence. Easy enough to change as noted above.

**Comment by NeverSinkDev** [comment]
Has been updated!
