### ISSUE TITLE
[Proposition] Add border for items with quality 

### ISSUE THREAD

**Issue by JakubSzczepek** [NeverSinkDev/NeverSink-Filter-for-PoE2#33]
Like:
Show
Quality > 0
SetBorderColor 0 255 218

On the beginning will be very good to catch that items and make quality shards to improve our items

**Comment by mfutselaar** [comment]
This seems easy enough to warrant a PR written by yourself @JakubSzczepek

**Comment by JakubSzczepek** [comment]
done
