### ISSUE TITLE
PS5 support?

### ISSUE THREAD

**Issue by opassos** [NeverSinkDev/NeverSink-Filter-for-PoE2#36]
Are there any hopes for PS5 support?

**Comment by NeverSinkDev** [comment]
I don't have any sharable news yet for console.

For that to happen, GGG has to enable the filter API... 
or grab a filter and deploy it onto consoles with a patch (like in PoE1)

That involves coordinating things with XBOS/PS5 etc and probably would only be announced if this is greenlit.

I don't have any news though.
