### ISSUE TITLE
Optional filters for targeting bases

### ISSUE THREAD

**Issue by jjones37** [NeverSinkDev/NeverSink-Filter-for-PoE2#39]
An optional section for targeting bases would be nice to have unless I'm missing it in the filter file.

``
#--------------------------
# End Game Bases
#--------------------------

# Weapon
Show
BaseType "Expert Slicing Quarterstaff" "Expert Long Quarterstaff"
SetTextColor 0 0 0
SetBorderColor 0 0 0  
SetBackgroundColor 52 201 235

# Gloves
Show
BaseType "Expert Gauze Wraps" "Expert Linen Wraps" "Expert Spiral Wraps"
SetTextColor 0 0 0
SetBorderColor 0 0 0  
SetBackgroundColor 52 201 235

# Boots
Show
BaseType "Expert Frayed Shoes" "Expert Threaded Shoes" "Expert Hunting Shoes"
SetTextColor 0 0 0
SetBorderColor 0 0 0  
SetBackgroundColor 52 201 235

# Body
Show
BaseType "Expert Vaal Cuirass" "Expert Pathfinder Coat" "Expert Studded Vest" "Expert Serpentscale Coat"
SetTextColor 0 0 0
SetBorderColor 0 0 0  
SetBackgroundColor 52 201 235

# Helmet
Show
BaseType "Expert Feathered Tiara" "Expert Chain Tiara" "Expert Wicker Tiara" "Expert Tribal Mask"
SetTextColor 0 0 0
SetBorderColor 0 0 0  
SetBackgroundColor 52 201 235
``

**Comment by NeverSinkDev** [comment]
I don't think I'll be adding them to this version as these are very specific to a certain playstyle, however, I'm building a more advanced endgame tiering system with the upcoming large filter.

Thank you for the suggestion regardless
