### ISSUE TITLE
Install instructions are not working on my windows install. 

### ISSUE THREAD

**Issue by KewkLW** [NeverSinkDev/NeverSink-Filter-for-PoE2#4]
This is more of an fyi if anyone has an issue with installing it.

`Paste the .filter files (or just the folder content, if you want to use a specific style, paste the files from one of the (STYLE) folders instead) into the following folder:`

There is no styles or content folders. 

These are the only folders. 
OnlineFilters (no sub dir's and adding the filter here did not work)
poe2_production

To get it to work I had to extract the .filter into "%userprofile%\Documents\My Games\Path of Exile 2" directly.

**Comment by tristandruyen** [comment]
The instructions seem to be copied over from the non-lite poe version, which does have the styles...

**Comment by bratzie** [comment]
I fixed this in #7 :) Instructions should be less confusing now.

**Comment by NeverSinkDev** [comment]
Was fixed by @bratzie , closed
