### ISSUE TITLE
Charm/rune highlight doesnt work

### ISSUE THREAD

**Issue by GregoryGH** [NeverSinkDev/NeverSink-Filter-for-PoE2#40]
Still white

**Comment by NeverSinkDev** [comment]
I think your monitor might have RGB issues, as I'm using a light blue color for those.
It works for sure.

**Comment by GregoryGH** [comment]
its not my monitor, its my eyes. they can mess up close colors :) could you please make some more distinctive color or add a border f.e. coz now i need to edit it after every update :(
