### ISSUE TITLE
Correction when installing

### ISSUE THREAD

**Issue by Russman7** [NeverSinkDev/NeverSink-Filter-for-PoE2#43]
This is more like a simple update on 'how' to install it. When installing the filter and you're placing the filter file, do not place it in the filters file (Docs> myGames> PoE2> (place here)> Onlinefilters). This generated some confusion on my part, since I placed all the filters under the Onlinefilters folder. I copied the file outside the folder to see if it would appear in game, to which it fixed this issue.

**Comment by Echo-Storm** [comment]
good update, it had me confused too, I installed it outside the folder on a hunch

**Comment by NeverSinkDev** [comment]
I've adjusted the readme, thanks
