### ISSUE TITLE
Filter effect looks different depending on input type

### ISSUE THREAD

**Issue by eullerpereira94** [NeverSinkDev/NeverSink-Filter-for-PoE2#51]
If the input type is set to controller, the highlighted items really pop from the undesired ones. When using WASD, there isn't that many differences. I haven't tested the filter with the keyboard and mouse input type.

One thing to note is that the font size used for the name of items on the ground when using a controller, is smaller than the font size when using WASD. I don't know if that's caused by the filter or the game.

**Comment by NeverSinkDev** [comment]
This is not something I have any control over.

GGG highlights items that are in clickable range on the controller as far as I'm aware
