### ISSUE TITLE
Orbs of Transmutation and Scrolls of Wisdom hidden

### ISSUE THREAD

**Issue by jchester4964** [NeverSinkDev/NeverSink-Filter-for-PoE2#53]
I've been playing with the filter for a few days now but realized I was running out of these two items; then I realized I hadn't seen them in a while either. I turned the filter off and the reappear.

Are these items supposed to be hidden? And if so, how do I alter that?

**Comment by tarasovyaroslav** [comment]
@jchester4964 I didn't find anything about orbs, but to stop hiding scrolls, you can open the filter file with a notepad and comment out (with the "#" symbol) the following lines, like that:
![image](https://github.com/user-attachments/assets/3bad5175-56e7-43bb-92b0-08f30959cf4a)

**Comment by jchester4964** [comment]
Thank you for your response. That solved the scroll issue, and the orbs started to show up again after altering the file for that alone. I didn't change any other code, so I don't understand what changed but it is no longer an issue.

**Comment by Samusia** [comment]
From release notes:
```
Added some hide rules for endgame mapping:

Scrolls of wisdom are now hidden in maps. Just buy them for 25 gold.
```
https://github.com/NeverSinkDev/NeverSink-PoE2litefilter/releases/tag/0.2.1

**Comment by NeverSinkDev** [comment]
Not an issue.

Transmutes were never hidden (check that highlight items is clicked in options)
