### ISSUE TITLE
[Question] Increased Rarity filter.

### ISSUE THREAD

**Issue by PauloGoncalvesLima** [NeverSinkDev/NeverSink-Filter-for-PoE2#54]
Is there a way to create a filter that displays items with "Increased Rarity of Items Found"?

Happy Holidays!

**Comment by NeverSinkDev** [comment]
There's technically a way to create a filter that highlights IDENTIFIED items with increased rarity of items found, however i'm not sure it's very useful, considering how few of those drop.
