### ISSUE TITLE
classes should be plural

### ISSUE THREAD

**Issue by KarateSnoopy** [NeverSinkDev/NeverSink-Filter-for-PoE2#8]
near the bottom you have:

Rarity <= Magic
Class "Flask" "Body" "Helmet" "Boots" "Gloves" "Shields" "Quiver" "Mace" "Staff" "Quarter" "Bow" "Crossbow" "Wand" "Sceptre"
AreaLevel >= 65

Show
Rarity <= Magic
Class "Flask" "Body" "Helmet" "Boots" "Gloves" "Shields" "Quiver" "Mace" "Staff" "Quarter" "Bow" "Crossbow" "Wand" "Sceptre"

but for it to work, it has to be plural class names something like this:

Hide
Rarity <= Magic
Class "Wands" "Shields" "Sceptres" "Foci" "One Hand Maces" "Two Hand Maces" "Staves" "Quarterstaves" "Quivers"

**Comment by TheAlexLichter** [comment]
@KarateSnoopy why not sending a PR? 👀
